### ISSUE TITLE
Grounding totem vs Shadowflame + Glyph

### ISSUE THREAD

**Issue by zanzaqtlol** [FALL1N1/HysteriaCore-IssueTracker#22]
The Grounding Totem, should work as Spell Reflect does, the slow effect most stay on the target, due the glyph effect, but, the periodic dmg, must be absorved by the totem effect.

**Comment by JunkyBulgaria** [comment]
stoneclaw totem redirects, not grounding

**Comment by FALL1N1** [comment]
fixed
