### ISSUE TITLE
Pilgrim's bounty Calendar data missing 

### ISSUE THREAD

**Issue by ghost** [FALL1N1/HysteriaCore-IssueTracker#25]
There is no event listed in ingame calendar. It should be there as the event began yesterday. Event alone is spawned and fine just the calendar note is missing. 
DBC related?

**Comment by FALL1N1** [comment]
non-fixable, WoTLK is quite old and it can not be added

**Comment by d3tr0l** [comment]
I noticed it is also working for example on gamer district wow. Idk, it can be related to calendar handlers or server dbc files. Can you take a look at this? Even if there is really dirty hackfix.
