### ISSUE TITLE
Leave No One Behind  - Quest ID:12512

### ISSUE THREAD

**Issue by mardkhar** [FALL1N1/HysteriaCore-IssueTracker#5]
http://www.wowhead.com/quest=12512/leave-no-one-behind

all quest is work fine
when u use [Crusader's Bandage](Item Quest)  to Three dead , deads will resp and follow u
and its work fine
but when u going to beside NPC (ID:28137) 0/1 Must go to 1/1

but when u go beside npc 28137 dont complete

**Comment by mardkhar** [comment]
and when u respawn dead , u have 3 min time for do quest and after 3min if u cant do quest , three respawn will dead again
and time too bug

**Comment by mardkhar** [comment]
check this quest tnx
its important quest , 4 player report this

**Comment by FALL1N1** [comment]
fixed
