### ISSUE TITLE
Quest:  [A Life Without Regret]

### ISSUE THREAD

**Issue by AnTOLI** [FALL1N1/HysteriaCore-IssueTracker#8]
Липсва Куеста http://www.wowhead.com/quest=13266/a-life-without-regret от Thrall http://wotlk.openwow.com/npc=4949 по прицип трябва да ме  вкара в друга фаза куеста за да мога да го взема от него. 
Намерих някакъв фикс дано да става. https://github.com/TrinityCore/TrinityCore/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8
Видео как става https://youtu.be/flPCbRZAaQI?t=1m15s

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
http://wotlk.openwow.com/npc=4949 Няма го Thrall не се вижда като съм до трона му го няма и само некви елити има http://www.wowhead.com/npc=31417/korkron-elite.
